// AUTO-GENERATED by scripts/seed/build-demo-dataset.ts — do not edit by hand.
// Sourced from the engine-validated synthetic corpus and enriched with IMO,
// counterparty, ETS scope, time-bar posture and evidence. Re-run the script to
// regenerate. 18 demo scenarios.
import type { SeedScenario } from "./seed-data";

export const seedScenarios: SeedScenario[] = [
{
  "vessel": "PACIFIC CREST",
  "vesselImo": "9315616",
  "voyageRef": "V23-870",
  "port": "Newcastle",
  "cargo": "Wheat in bulk, 6,500 MT",
  "counterpartyName": "Cargill Ocean Transportation",
  "cpForm": "GENCON94",
  "cpTerms": {
    "laytime_allowed_hours": 26,
    "load_rate": 6000,
    "discharge_rate": 6000,
    "turn_time_hours": 6,
    "nor_variant": "WIBON",
    "days_basis": "SHINC",
    "demurrage_rate": 39500,
    "despatch_rate": 19750,
    "currency": "USD",
    "port_timezone": "Australia/Sydney"
  },
  "timeBarDays": 90,
  "recencyDays": 21,
  "etsApplicable": false,
  "archetype": "clean-shinc-demurrage",
  "description": "Clean SHINC voyage overrunning its allowance — straight demurrage.",
  "weatherVerdict": null,
  "events": [
    {
      "occurred_at": "2023-11-08T23:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "Notice of Readiness tendered",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9400000000000001,
      "reasoning": "Clean SHINC voyage overrunning its allowance — straight demurrage."
    },
    {
      "occurred_at": "2023-11-09T03:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "All fast",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.97,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-09T06:00:00.000Z",
      "event_type": "COMMENCED_DISCHARGE",
      "verbatim": "Discharge commenced",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.92,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-14T01:00:00.000Z",
      "event_type": "COMPLETED_DISCHARGE",
      "verbatim": "Completed discharge",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9500000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "GRAND VOYAGER",
  "vesselImo": "9436733",
  "voyageRef": "V26-077",
  "port": "Singapore",
  "cargo": "Wheat in bulk, 5,800 MT",
  "counterpartyName": "Bunge Chartering S.A.",
  "cpForm": "GENCON94",
  "cpTerms": {
    "laytime_allowed_hours": 14,
    "load_rate": 10000,
    "discharge_rate": 3000,
    "turn_time_hours": 6,
    "nor_variant": "WIBON",
    "days_basis": "SHINC",
    "demurrage_rate": 33500,
    "despatch_rate": 16750,
    "currency": "USD",
    "port_timezone": "Asia/Singapore"
  },
  "timeBarDays": 90,
  "recencyDays": 29,
  "etsApplicable": false,
  "archetype": "clean-shinc-demurrage",
  "description": "Clean SHINC voyage overrunning its allowance — straight demurrage.",
  "weatherVerdict": null,
  "events": [
    {
      "occurred_at": "2023-11-08T02:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "NOR tendered by Master",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9500000000000001,
      "reasoning": "Clean SHINC voyage overrunning its allowance — straight demurrage."
    },
    {
      "occurred_at": "2023-11-08T06:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "Vessel all fast, gangway secured",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.92,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-08T07:00:00.000Z",
      "event_type": "HATCH_OPEN",
      "verbatim": "Hatches opened",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.97,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-08T08:00:00.000Z",
      "event_type": "COMMENCED_LOADING",
      "verbatim": "Commenced loading",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9400000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-09T20:00:00.000Z",
      "event_type": "COMPLETED_LOADING",
      "verbatim": "Completed loading",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.91,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "BALTIC TRADER",
  "vesselImo": "9151462",
  "voyageRef": "V25-126",
  "port": "Rotterdam",
  "cargo": "Corn in bulk, 30,200 MT",
  "counterpartyName": "Trafigura Maritime Logistics Pte Ltd",
  "cpForm": "GENCON94",
  "cpTerms": {
    "laytime_allowed_hours": 145,
    "load_rate": 5000,
    "discharge_rate": 4000,
    "turn_time_hours": 6,
    "nor_variant": "WIBON",
    "days_basis": "SHINC",
    "demurrage_rate": 29500,
    "despatch_rate": 14750,
    "currency": "USD",
    "port_timezone": "Europe/Amsterdam"
  },
  "timeBarDays": 90,
  "recencyDays": 37,
  "etsApplicable": true,
  "archetype": "clean-shinc-despatch",
  "description": "Clean SHINC voyage completing early — despatch payable.",
  "weatherVerdict": null,
  "events": [
    {
      "occurred_at": "2025-12-04T05:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "NOR tendered by Master",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9400000000000001,
      "reasoning": "Clean SHINC voyage completing early — despatch payable."
    },
    {
      "occurred_at": "2025-12-04T10:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "Vessel all fast alongside berth",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.97,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-12-04T13:00:00.000Z",
      "event_type": "COMMENCED_LOADING",
      "verbatim": "Commenced loading",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.92,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-12-09T05:00:00.000Z",
      "event_type": "COMPLETED_LOADING",
      "verbatim": "Loading completed, cargo documents on board",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9500000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "CORAL EMPRESS",
  "vesselImo": "9880166",
  "voyageRef": "V24-533",
  "port": "Richards Bay",
  "cargo": "Bauxite, 57,000 MT",
  "counterpartyName": "Louis Dreyfus Company Suisse S.A.",
  "cpForm": "GENCON94",
  "cpTerms": {
    "laytime_allowed_hours": 152,
    "load_rate": 9000,
    "discharge_rate": 10000,
    "turn_time_hours": 12,
    "nor_variant": "WIBON",
    "days_basis": "SHINC",
    "demurrage_rate": 35000,
    "despatch_rate": 17500,
    "currency": "USD",
    "port_timezone": "Africa/Johannesburg"
  },
  "timeBarDays": 90,
  "recencyDays": 45,
  "etsApplicable": false,
  "archetype": "clean-shinc-despatch",
  "description": "Clean SHINC voyage completing early — despatch payable.",
  "weatherVerdict": null,
  "events": [
    {
      "occurred_at": "2025-05-03T04:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "NOR tendered and accepted by agents",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9500000000000001,
      "reasoning": "Clean SHINC voyage completing early — despatch payable."
    },
    {
      "occurred_at": "2025-05-03T08:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "All fast",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.92,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-05-03T10:00:00.000Z",
      "event_type": "COMMENCED_LOADING",
      "verbatim": "Commenced loading",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.97,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-05-06T22:00:00.000Z",
      "event_type": "COMPLETED_LOADING",
      "verbatim": "Loading completed, cargo documents on board",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9400000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "GOLDEN WAVE",
  "vesselImo": "9861574",
  "voyageRef": "V23-202",
  "port": "Newcastle",
  "cargo": "Corn in bulk, 19,900 MT",
  "counterpartyName": "Glencore International AG",
  "cpForm": "GENCON94",
  "cpTerms": {
    "laytime_allowed_hours": 53,
    "load_rate": 4000,
    "discharge_rate": 9000,
    "turn_time_hours": 6,
    "nor_variant": "WIBON",
    "days_basis": "WWDSHEX-EIU",
    "demurrage_rate": 27000,
    "despatch_rate": 13500,
    "currency": "USD",
    "port_timezone": "Australia/Sydney"
  },
  "timeBarDays": 90,
  "recencyDays": 25,
  "etsApplicable": false,
  "archetype": "weather-wwd-excluded",
  "description": "WWDSHEX-EIU: logged weather interruptions excluded from laytime.",
  "weatherVerdict": "contradicted",
  "events": [
    {
      "occurred_at": "2025-11-02T21:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "Notice of Readiness tendered",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.92,
      "reasoning": "WWDSHEX-EIU: logged weather interruptions excluded from laytime."
    },
    {
      "occurred_at": "2025-11-02T23:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "Vessel all fast, gangway secured",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9500000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-11-03T01:00:00.000Z",
      "event_type": "COMMENCED_DISCHARGE",
      "verbatim": "Commenced discharge",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9400000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-11-03T08:00:00.000Z",
      "event_type": "WEATHER_DELAY",
      "verbatim": "High winds, cranes secured — work stopped",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.97,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-11-03T11:00:00.000Z",
      "event_type": "WEATHER_DELAY_END",
      "verbatim": "Weather improved — work resumed",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.96,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-11-03T15:00:00.000Z",
      "event_type": "WEATHER_DELAY",
      "verbatim": "High winds, cranes secured — work stopped",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.91,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-11-03T19:00:00.000Z",
      "event_type": "WEATHER_DELAY_END",
      "verbatim": "Weather improved — work resumed",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-11-05T15:00:00.000Z",
      "event_type": "COMPLETED_DISCHARGE",
      "verbatim": "Discharge completed, holds swept clean",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.93,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "CAPE MERIDIAN",
  "vesselImo": "9024683",
  "voyageRef": "V25-442",
  "port": "Gibraltar",
  "cargo": "Steam coal, 27,900 MT",
  "counterpartyName": "Oldendorff Carriers GmbH & Co. KG",
  "cpForm": "GENCON94",
  "cpTerms": {
    "laytime_allowed_hours": 67,
    "load_rate": 10000,
    "discharge_rate": 7000,
    "turn_time_hours": 12,
    "nor_variant": "WIBON",
    "days_basis": "WWDSHEX-EIU",
    "demurrage_rate": 30500,
    "despatch_rate": 15250,
    "currency": "USD",
    "port_timezone": "Europe/Gibraltar"
  },
  "timeBarDays": 90,
  "recencyDays": 33,
  "etsApplicable": false,
  "archetype": "weather-wwd-excluded",
  "description": "WWDSHEX-EIU: logged weather interruptions excluded from laytime.",
  "weatherVerdict": "corroborated",
  "events": [
    {
      "occurred_at": "2025-09-01T06:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "Notice of Readiness tendered",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.97,
      "reasoning": "WWDSHEX-EIU: logged weather interruptions excluded from laytime."
    },
    {
      "occurred_at": "2025-09-01T11:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "Vessel all fast, gangway secured",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9400000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-09-01T12:00:00.000Z",
      "event_type": "COMMENCED_LOADING",
      "verbatim": "Commenced loading",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9500000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-09-01T20:00:00.000Z",
      "event_type": "WEATHER_DELAY",
      "verbatim": "High winds, cranes secured — work stopped",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.92,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-09-02T00:00:00.000Z",
      "event_type": "WEATHER_DELAY_END",
      "verbatim": "Weather improved — work resumed",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.93,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-09-02T10:00:00.000Z",
      "event_type": "WEATHER_DELAY",
      "verbatim": "Heavy swell, cargo operations suspended",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-09-02T13:00:00.000Z",
      "event_type": "WEATHER_DELAY_END",
      "verbatim": "Weather moderated, operations resumed",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.91,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-09-03T00:00:00.000Z",
      "event_type": "WEATHER_DELAY",
      "verbatim": "High winds, cranes secured — work stopped",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.96,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-09-03T03:00:00.000Z",
      "event_type": "WEATHER_DELAY_END",
      "verbatim": "Weather moderated, operations resumed",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.97,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-09-04T15:00:00.000Z",
      "event_type": "COMPLETED_LOADING",
      "verbatim": "Loading completed, cargo documents on board",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9400000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "SILVER GULL",
  "vesselImo": "9854181",
  "voyageRef": "V24-948",
  "port": "Richards Bay",
  "cargo": "Iron ore fines, 2,300 MT",
  "counterpartyName": "Rio Tinto Shipping Pte Ltd",
  "cpForm": "GENCON94",
  "cpTerms": {
    "laytime_allowed_hours": 9,
    "load_rate": 6000,
    "discharge_rate": 6000,
    "turn_time_hours": 6,
    "nor_variant": "WIBON",
    "days_basis": "SHINC",
    "demurrage_rate": 21500,
    "despatch_rate": 10750,
    "currency": "USD",
    "port_timezone": "Africa/Johannesburg"
  },
  "timeBarDays": 90,
  "recencyDays": 41,
  "etsApplicable": false,
  "archetype": "weather-on-demurrage-counts",
  "description": "GENCON 94 Cl.8: once on demurrage, weather does not interrupt — the weather window bills at the full rate.",
  "weatherVerdict": "contradicted",
  "events": [
    {
      "occurred_at": "2024-09-23T06:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "Notice of Readiness tendered",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.92,
      "reasoning": "GENCON 94 Cl.8: once on demurrage, weather does not interrupt — the weather window bills at the full rate."
    },
    {
      "occurred_at": "2024-09-23T11:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "Vessel all fast, gangway secured",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9500000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2024-09-23T12:00:00.000Z",
      "event_type": "COMMENCED_LOADING",
      "verbatim": "Loading commenced all hatches",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9400000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2024-09-24T11:00:00.000Z",
      "event_type": "WEATHER_DELAY",
      "verbatim": "Heavy swell, cargo operations suspended",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.97,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2024-09-24T19:00:00.000Z",
      "event_type": "WEATHER_DELAY_END",
      "verbatim": "Weather improved — work resumed",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.96,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2024-09-25T15:00:00.000Z",
      "event_type": "COMPLETED_LOADING",
      "verbatim": "Loading completed, cargo documents on board",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.91,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "CRIMSON TIDE",
  "vesselImo": "9418365",
  "voyageRef": "V24-853",
  "port": "Rotterdam",
  "cargo": "Wheat in bulk, 52,100 MT",
  "counterpartyName": "COFCO Resources S.A.",
  "cpForm": "GENCON94",
  "cpTerms": {
    "laytime_allowed_hours": 125,
    "load_rate": 11000,
    "discharge_rate": 10000,
    "turn_time_hours": 6,
    "nor_variant": "WIBON",
    "days_basis": "SHEX",
    "demurrage_rate": 21500,
    "despatch_rate": 10750,
    "currency": "EUR",
    "port_timezone": "Europe/Amsterdam"
  },
  "timeBarDays": 90,
  "recencyDays": 21,
  "etsApplicable": true,
  "archetype": "shex-sunday-excluded",
  "description": "SHEX: Sunday excluded while the allowance still runs.",
  "weatherVerdict": null,
  "events": [
    {
      "occurred_at": "2024-07-05T06:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "NOR tendered by Master",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9,
      "reasoning": "SHEX: Sunday excluded while the allowance still runs."
    },
    {
      "occurred_at": "2024-07-05T12:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "All fast",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.93,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2024-07-05T13:00:00.000Z",
      "event_type": "COMMENCED_DISCHARGE",
      "verbatim": "Commenced discharge",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.96,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2024-07-09T18:00:00.000Z",
      "event_type": "COMPLETED_DISCHARGE",
      "verbatim": "Completed discharge",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.91,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "CORAL EMPRESS",
  "vesselImo": "9126780",
  "voyageRef": "V24-023",
  "port": "Qingdao",
  "cargo": "Bauxite, 29,000 MT",
  "counterpartyName": "ADM International Sàrl",
  "cpForm": "GENCON94",
  "cpTerms": {
    "laytime_allowed_hours": 116,
    "load_rate": 5000,
    "discharge_rate": 6000,
    "turn_time_hours": 6,
    "nor_variant": "WIBON",
    "days_basis": "SSHEX-UU",
    "demurrage_rate": 35500,
    "despatch_rate": 17750,
    "currency": "USD",
    "port_timezone": "Asia/Shanghai"
  },
  "timeBarDays": 90,
  "recencyDays": 29,
  "etsApplicable": false,
  "archetype": "shex-uu-worked-counts",
  "description": "SHEX-UU with hatches open and cargo working through the weekend: excepted hours count (Cl.7(d)).",
  "weatherVerdict": null,
  "events": [
    {
      "occurred_at": "2025-01-17T00:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "NOR tendered by Master",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.93,
      "reasoning": "SHEX-UU with hatches open and cargo working through the weekend: excepted hours count (Cl.7(d))."
    },
    {
      "occurred_at": "2025-01-17T06:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "Vessel all fast alongside berth",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-01-17T07:00:00.000Z",
      "event_type": "HATCH_OPEN",
      "verbatim": "Hatches opened",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.91,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-01-17T07:00:00.000Z",
      "event_type": "COMMENCED_DISCHARGE",
      "verbatim": "Commenced discharge",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.96,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-01-20T21:00:00.000Z",
      "event_type": "COMPLETED_DISCHARGE",
      "verbatim": "Completed discharge",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.97,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "MISTRAL WIND",
  "vesselImo": "9581992",
  "voyageRef": "V26-907",
  "port": "Singapore",
  "cargo": "Urea prills, 36,700 MT",
  "counterpartyName": "Vitol S.A.",
  "cpForm": "GENCON94",
  "cpTerms": {
    "laytime_allowed_hours": 110,
    "load_rate": 8000,
    "discharge_rate": 9000,
    "turn_time_hours": 6,
    "nor_variant": "WIBON",
    "days_basis": "SSHEX",
    "demurrage_rate": 27000,
    "despatch_rate": 13500,
    "currency": "USD",
    "port_timezone": "Asia/Singapore"
  },
  "timeBarDays": 90,
  "recencyDays": 37,
  "etsApplicable": false,
  "archetype": "sshex-weekend-excluded",
  "description": "SSHEX: Saturdays and Sundays excluded while the allowance still runs.",
  "weatherVerdict": null,
  "events": [
    {
      "occurred_at": "2025-06-13T00:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "NOR tendered and accepted by agents",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.96,
      "reasoning": "SSHEX: Saturdays and Sundays excluded while the allowance still runs."
    },
    {
      "occurred_at": "2025-06-13T02:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "Vessel all fast, gangway secured",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.91,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-06-13T04:00:00.000Z",
      "event_type": "COMMENCED_LOADING",
      "verbatim": "Commenced loading",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-06-16T21:00:00.000Z",
      "event_type": "COMPLETED_LOADING",
      "verbatim": "Loading completed, cargo documents on board",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.93,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "GRAND VOYAGER",
  "vesselImo": "9145592",
  "voyageRef": "V26-454",
  "port": "Santos",
  "cargo": "Iron ore fines, 14,600 MT",
  "counterpartyName": "Gunvor SA",
  "cpForm": "GENCON94",
  "cpTerms": {
    "laytime_allowed_hours": 35,
    "load_rate": 10000,
    "discharge_rate": 5000,
    "turn_time_hours": 6,
    "nor_variant": "WIBON",
    "days_basis": "SHINC",
    "demurrage_rate": 25500,
    "despatch_rate": 12750,
    "currency": "USD",
    "port_timezone": "America/Sao_Paulo"
  },
  "timeBarDays": 90,
  "recencyDays": 45,
  "etsApplicable": false,
  "archetype": "wibon-shifting-counts",
  "description": "WIBON: shifting from anchorage to berth counts as laytime.",
  "weatherVerdict": null,
  "events": [
    {
      "occurred_at": "2025-02-03T11:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "NOR tendered and accepted by agents",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.93,
      "reasoning": "WIBON: shifting from anchorage to berth counts as laytime."
    },
    {
      "occurred_at": "2025-02-03T17:00:00.000Z",
      "event_type": "SHIFTING",
      "verbatim": "Vessel shifting to working berth",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-02-03T22:00:00.000Z",
      "event_type": "SHIFTING_END",
      "verbatim": "Shifting completed, vessel in position",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.91,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-02-03T22:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "Vessel all fast, gangway secured",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.96,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-02-04T01:00:00.000Z",
      "event_type": "COMMENCED_LOADING",
      "verbatim": "Commenced loading",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.97,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-02-05T14:00:00.000Z",
      "event_type": "COMPLETED_LOADING",
      "verbatim": "Loading completed, cargo documents on board",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9400000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "POLARIS QUEEN",
  "vesselImo": "9227209",
  "voyageRef": "V26-914",
  "port": "Houston",
  "cargo": "Wheat in bulk, 15,800 MT",
  "counterpartyName": "Klaveness Combination Carriers",
  "cpForm": "GENCON94",
  "cpTerms": {
    "laytime_allowed_hours": 63,
    "load_rate": 6000,
    "discharge_rate": 10000,
    "turn_time_hours": 6,
    "nor_variant": "WIBON",
    "days_basis": "SHEX",
    "demurrage_rate": 32500,
    "despatch_rate": 16250,
    "currency": "EUR",
    "port_timezone": "America/Chicago"
  },
  "timeBarDays": 90,
  "recencyDays": 25,
  "etsApplicable": false,
  "archetype": "port-strike-excepted",
  "description": "Stevedores' strike logged as an excepted period — excluded from laytime under SHEX.",
  "weatherVerdict": null,
  "events": [
    {
      "occurred_at": "2024-11-25T14:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "NOR tendered by Master",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.93,
      "reasoning": "Stevedores' strike logged as an excepted period — excluded from laytime under SHEX."
    },
    {
      "occurred_at": "2024-11-25T19:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "Vessel all fast alongside berth",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2024-11-25T22:00:00.000Z",
      "event_type": "COMMENCED_LOADING",
      "verbatim": "Loading commenced all hatches",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.91,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2024-11-26T08:00:00.000Z",
      "event_type": "EXCEPTED_PERIOD_START",
      "verbatim": "Stevedores' strike commenced — all work stopped",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.96,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2024-11-26T19:00:00.000Z",
      "event_type": "EXCEPTED_PERIOD_END",
      "verbatim": "Industrial action lifted, operations resumed",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.97,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2024-11-28T00:00:00.000Z",
      "event_type": "COMPLETED_LOADING",
      "verbatim": "Completed loading",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9400000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "GRAND VOYAGER",
  "vesselImo": "9740598",
  "voyageRef": "V25-437",
  "port": "Santos",
  "cargo": "Gasoil, 11,000 MT",
  "counterpartyName": "NYK Bulkship (Asia) Pte Ltd",
  "cpForm": "ASBATANKVOY",
  "cpTerms": {
    "laytime_allowed_hours": 24,
    "load_rate": 11000,
    "discharge_rate": 6000,
    "turn_time_hours": 6,
    "nor_variant": "WIBON",
    "days_basis": "SHINC",
    "demurrage_rate": 27000,
    "despatch_rate": 13500,
    "currency": "USD",
    "port_timezone": "America/Sao_Paulo",
    "cp_form": "ASBATANKVOY"
  },
  "timeBarDays": 90,
  "recencyDays": 33,
  "etsApplicable": false,
  "archetype": "asba-running-hours",
  "description": "ASBATANKVOY running hours: Sundays included, laytime runs continuously.",
  "weatherVerdict": null,
  "events": [
    {
      "occurred_at": "2025-08-23T17:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "NOR tendered and accepted by agents",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9500000000000001,
      "reasoning": "ASBATANKVOY running hours: Sundays included, laytime runs continuously."
    },
    {
      "occurred_at": "2025-08-24T05:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "Vessel all fast alongside berth",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.92,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-08-24T06:00:00.000Z",
      "event_type": "COMMENCED_LOADING",
      "verbatim": "Commenced loading",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.97,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2025-08-26T06:00:00.000Z",
      "event_type": "COMPLETED_LOADING",
      "verbatim": "Completed loading",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9400000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "IRON DUKE",
  "vesselImo": "9474993",
  "voyageRef": "V23-638",
  "port": "Houston",
  "cargo": "Fuel oil 380cst, 3,800 MT",
  "counterpartyName": "Pacific Basin Chartering Ltd",
  "cpForm": "ASBATANKVOY",
  "cpTerms": {
    "laytime_allowed_hours": 10,
    "load_rate": 4000,
    "discharge_rate": 9000,
    "turn_time_hours": 6,
    "nor_variant": "WIBON",
    "days_basis": "SHINC",
    "demurrage_rate": 39500,
    "despatch_rate": 19750,
    "currency": "EUR",
    "port_timezone": "America/Chicago",
    "cp_form": "ASBATANKVOY"
  },
  "timeBarDays": 90,
  "recencyDays": 41,
  "etsApplicable": false,
  "archetype": "asba-half-rate-demurrage",
  "description": "ASBATANKVOY Cl.8: storm while on demurrage — those hours bill at half the demurrage rate.",
  "weatherVerdict": null,
  "events": [
    {
      "occurred_at": "2024-08-22T13:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "NOR tendered by Master",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.93,
      "reasoning": "ASBATANKVOY Cl.8: storm while on demurrage — those hours bill at half the demurrage rate."
    },
    {
      "occurred_at": "2024-08-22T15:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "All fast",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2024-08-22T15:00:00.000Z",
      "event_type": "COMMENCED_DISCHARGE",
      "verbatim": "Discharge commenced",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.91,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2024-08-23T05:00:00.000Z",
      "event_type": "WEATHER_DELAY",
      "verbatim": "Rain — all work stopped",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.96,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2024-08-23T10:00:00.000Z",
      "event_type": "WEATHER_DELAY_END",
      "verbatim": "Weather moderated, operations resumed",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.97,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2024-08-23T20:00:00.000Z",
      "event_type": "COMPLETED_DISCHARGE",
      "verbatim": "Completed discharge",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9400000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "IRON DUKE",
  "vesselImo": "9066045",
  "voyageRef": "V25-618",
  "port": "Rotterdam",
  "cargo": "Wheat in bulk, 25,100 MT",
  "counterpartyName": "Norden Tankers & Bulkers",
  "cpForm": "GENCON94",
  "cpTerms": {
    "laytime_allowed_hours": 86,
    "load_rate": 12000,
    "discharge_rate": 7000,
    "turn_time_hours": 6,
    "nor_variant": "WIBON",
    "days_basis": "WWDSHEX-EIU",
    "demurrage_rate": 42500,
    "despatch_rate": 21250,
    "currency": "EUR",
    "port_timezone": "Europe/Amsterdam"
  },
  "timeBarDays": 90,
  "recencyDays": 21,
  "etsApplicable": true,
  "archetype": "multi-interruption-stress",
  "description": "Stress case: shifting + weather + weekend (and sometimes a strike) stacked in one WWDSHEX-EIU voyage.",
  "weatherVerdict": null,
  "events": [
    {
      "occurred_at": "2023-11-17T07:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "Notice of Readiness tendered",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.92,
      "reasoning": "Stress case: shifting + weather + weekend (and sometimes a strike) stacked in one WWDSHEX-EIU voyage."
    },
    {
      "occurred_at": "2023-11-17T13:00:00.000Z",
      "event_type": "SHIFTING",
      "verbatim": "Vessel shifting to working berth",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9500000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-17T15:00:00.000Z",
      "event_type": "SHIFTING_END",
      "verbatim": "Completed shifting",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9400000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-17T15:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "Vessel all fast, gangway secured",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.97,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-17T16:00:00.000Z",
      "event_type": "HATCH_OPEN",
      "verbatim": "Hatches opened",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.96,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-17T17:00:00.000Z",
      "event_type": "COMMENCED_DISCHARGE",
      "verbatim": "Commenced discharge",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.91,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-17T23:00:00.000Z",
      "event_type": "WEATHER_DELAY",
      "verbatim": "High winds, cranes secured — work stopped",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-18T01:00:00.000Z",
      "event_type": "WEATHER_DELAY_END",
      "verbatim": "Weather improved — work resumed",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.93,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-18T07:00:00.000Z",
      "event_type": "EXCEPTED_PERIOD_START",
      "verbatim": "Stevedores' strike commenced — all work stopped",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.92,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-18T12:00:00.000Z",
      "event_type": "EXCEPTED_PERIOD_END",
      "verbatim": "Industrial action lifted, operations resumed",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9500000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-22T06:00:00.000Z",
      "event_type": "COMPLETED_DISCHARGE",
      "verbatim": "Completed discharge",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.97,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "BALTIC TRADER",
  "vesselImo": "9561617",
  "voyageRef": "V25-430",
  "port": "Richards Bay",
  "cargo": "Steam coal, 11,300 MT",
  "counterpartyName": "Ultrabulk A/S",
  "cpForm": "GENCON94",
  "cpTerms": {
    "laytime_allowed_hours": 68,
    "load_rate": 4000,
    "discharge_rate": 7000,
    "turn_time_hours": 6,
    "nor_variant": "WIBON",
    "days_basis": "SHINC",
    "demurrage_rate": 43500,
    "despatch_rate": 21750,
    "currency": "USD",
    "port_timezone": "Africa/Johannesburg"
  },
  "timeBarDays": 90,
  "recencyDays": 76,
  "etsApplicable": false,
  "archetype": "timebar-warning",
  "description": "Time-bar countdown in the \"warning\" band (90-day bar). Clean SHINC voyage overrunning its allowance — straight demurrage.",
  "weatherVerdict": null,
  "events": [
    {
      "occurred_at": "2023-11-04T08:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "Notice of Readiness tendered",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.91,
      "reasoning": "Time-bar countdown in the \"warning\" band (90-day bar). Clean SHINC voyage overrunning its allowance — straight demurrage."
    },
    {
      "occurred_at": "2023-11-04T10:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "Vessel all fast alongside berth",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.96,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-04T11:00:00.000Z",
      "event_type": "HATCH_OPEN",
      "verbatim": "All hatches open, ready for cargo",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.93,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-04T12:00:00.000Z",
      "event_type": "COMMENCED_LOADING",
      "verbatim": "Commenced loading",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2023-11-09T11:00:00.000Z",
      "event_type": "COMPLETED_LOADING",
      "verbatim": "Loading completed, cargo documents on board",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9500000000000001,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "POLARIS QUEEN",
  "vesselImo": "9749697",
  "voyageRef": "V23-182",
  "port": "Newcastle",
  "cargo": "Corn in bulk, 6,300 MT",
  "counterpartyName": "Western Bulk Carriers",
  "cpForm": "GENCON94",
  "cpTerms": {
    "laytime_allowed_hours": 19,
    "load_rate": 8000,
    "discharge_rate": 9000,
    "turn_time_hours": 12,
    "nor_variant": "WIBON",
    "days_basis": "SHINC",
    "demurrage_rate": 34500,
    "despatch_rate": 17250,
    "currency": "USD",
    "port_timezone": "Australia/Sydney"
  },
  "timeBarDays": 90,
  "recencyDays": 86,
  "etsApplicable": false,
  "archetype": "timebar-critical",
  "description": "Time-bar countdown in the \"critical\" band (90-day bar). Clean SHINC voyage overrunning its allowance — straight demurrage.",
  "weatherVerdict": null,
  "events": [
    {
      "occurred_at": "2024-04-01T19:30:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "NOR tendered and accepted by agents",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.96,
      "reasoning": "Time-bar countdown in the \"critical\" band (90-day bar). Clean SHINC voyage overrunning its allowance — straight demurrage."
    },
    {
      "occurred_at": "2024-04-02T01:30:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "Vessel all fast, gangway secured",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.91,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2024-04-02T04:30:00.000Z",
      "event_type": "COMMENCED_LOADING",
      "verbatim": "Loading commenced all hatches",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2024-04-04T08:30:00.000Z",
      "event_type": "COMPLETED_LOADING",
      "verbatim": "Loading completed, cargo documents on board",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.93,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
},
{
  "vessel": "IRON DUKE",
  "vesselImo": "9813125",
  "voyageRef": "V25-116",
  "port": "Houston",
  "cargo": "Corn in bulk, 1,400 MT",
  "counterpartyName": "Swiss Marine Services S.A.",
  "cpForm": "GENCON94",
  "cpTerms": {
    "laytime_allowed_hours": 11,
    "load_rate": 5000,
    "discharge_rate": 3000,
    "turn_time_hours": 12,
    "nor_variant": "WIBON",
    "days_basis": "SHINC",
    "demurrage_rate": 31000,
    "despatch_rate": 15500,
    "currency": "USD",
    "port_timezone": "America/Chicago"
  },
  "timeBarDays": 90,
  "recencyDays": 128,
  "etsApplicable": false,
  "archetype": "timebar-expired",
  "description": "Time-bar countdown in the \"expired\" band (60-day bar). Clean SHINC voyage overrunning its allowance — straight demurrage.",
  "weatherVerdict": null,
  "events": [
    {
      "occurred_at": "2026-01-04T14:00:00.000Z",
      "event_type": "NOR_TENDERED",
      "verbatim": "Notice of Readiness tendered",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.96,
      "reasoning": "Time-bar countdown in the \"expired\" band (60-day bar). Clean SHINC voyage overrunning its allowance — straight demurrage."
    },
    {
      "occurred_at": "2026-01-04T20:00:00.000Z",
      "event_type": "ALL_FAST",
      "verbatim": "Vessel all fast alongside berth",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.91,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2026-01-04T21:00:00.000Z",
      "event_type": "COMMENCED_DISCHARGE",
      "verbatim": "Discharge commenced",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.9,
      "reasoning": "Extracted from the Statement of Facts."
    },
    {
      "occurred_at": "2026-01-07T09:00:00.000Z",
      "event_type": "COMPLETED_DISCHARGE",
      "verbatim": "Completed discharge",
      "page": 1,
      "bbox": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "confidence": 0.93,
      "reasoning": "Extracted from the Statement of Facts."
    }
  ]
}
] as SeedScenario[];
