#!/usr/bin/env bun
// Copies pdf.js's runtime assets out of node_modules and into public/, so the
// app serves them itself.
//
// pdf.js does not bundle these. They are fetched at runtime from URLs the
// caller supplies (cMapUrl / standardFontDataUrl / wasmUrl), and every one of
// those parameters defaults to NULL — when a document needs one and it was
// never configured, pdf.js throws "Ensure that the `wasmUrl` API parameter is
// provided." That failure is document-dependent, which is what makes it
// dangerous: a text-layer PDF renders perfectly and a scanned one does not.
//
//   wasm/           JBIG2 + JPEG2000 decoders. Scanned Statements of Facts —
//                   the product's core input — are exactly what needs these.
//   cmaps/          Character maps for CJK and other non-Latin encodings.
//                   Port agents in CN/JP/KR routinely send such PDFs.
//   standard_fonts/ The base-14 fonts, for documents that do not embed them.
//
// Generated, not committed (public/pdfjs is gitignored): copying binaries into
// git by hand is how they drift from the installed version. This runs from
// `bun run dev` and `bun run build` so the tree is always rebuilt from the
// pdfjs-dist actually installed. It also refreshes the worker and reports when
// that changed, since the worker MUST match the library version.

import { existsSync } from "node:fs";
import { cp, mkdir, rm, readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";

const require = createRequire(import.meta.url);
const pkgJsonPath = require.resolve("pdfjs-dist/package.json");
const PDFJS_DIR = path.dirname(pkgJsonPath);
const VERSION = JSON.parse(await readFile(pkgJsonPath, "utf8")).version as string;

const PUBLIC_DIR = path.join(process.cwd(), "public");
// A dedicated directory, so the wipe below can never touch anything else in
// public/ — this script deletes a tree, and it must only ever be its own.
const OUT_DIR = path.join(PUBLIC_DIR, "pdfjs");

const ASSET_DIRS = ["wasm", "cmaps", "standard_fonts"] as const;

async function main() {
  const missing = ASSET_DIRS.filter((d) => !existsSync(path.join(PDFJS_DIR, d)));
  if (missing.length) {
    console.error(
      `[pdfjs] pdfjs-dist ${VERSION} is missing: ${missing.join(", ")}. ` +
        `Asset layout changed — update this script rather than shipping a build that cannot render scanned PDFs.`
    );
    process.exit(1);
  }

  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  for (const dir of ASSET_DIRS) {
    await cp(path.join(PDFJS_DIR, dir), path.join(OUT_DIR, dir), { recursive: true });
  }

  // The worker is committed at public/pdf.worker.min.mjs (it predates this
  // script). Refresh it in place and say so when it changed: a worker from a
  // different release than the library fails in obscure ways.
  const workerSrc = path.join(PDFJS_DIR, "build", "pdf.worker.min.mjs");
  const workerDest = path.join(PUBLIC_DIR, "pdf.worker.min.mjs");
  const incoming = await readFile(workerSrc);
  const existing = existsSync(workerDest) ? await readFile(workerDest) : null;
  const workerChanged = !existing || !existing.equals(incoming);
  if (workerChanged) await writeFile(workerDest, incoming);

  // A stamp so a stale tree is identifiable without diffing binaries.
  await writeFile(
    path.join(OUT_DIR, "VERSION"),
    `pdfjs-dist ${VERSION}\ngenerated by scripts/sync-pdfjs-assets.ts — do not edit or commit\n`
  );

  console.log(
    `[pdfjs] synced ${ASSET_DIRS.join(", ")} for pdfjs-dist ${VERSION} → public/pdfjs/` +
      (workerChanged ? "\n[pdfjs] worker UPDATED at public/pdf.worker.min.mjs — commit it" : "")
  );
}

await main();
