-- Phase 7 / Epic C Part 3 — agreed claims and settlement payloads.
--
-- `claims.status` has no 'agreed' value, and agreement was previously implicit
-- in `evaluateEligibility()` — derived state a trigger cannot compute (it needs
-- evidence checks, proposals and the calculation). This adds the real state
-- transition the outbox can observe.

-- === 1. The agreement transition ===
--
-- Nullable and not backfilled: an unagreed claim is the normal case, and
-- inventing an agreement date for historical claims would emit settlement
-- events for money nobody agreed to move.

alter table public.claims add column if not exists agreed_at timestamptz;
alter table public.claims add column if not exists agreed_by uuid references auth.users (id);
-- The calculation that was agreed. A later recompute changes the numbers, and
-- settling against the wrong snapshot is the failure this pins down.
alter table public.claims add column if not exists agreed_calculation_id uuid;

create index if not exists idx_claims_agreed
  on public.claims (company_id, agreed_at)
  where agreed_at is not null;

-- === 2. Settlement payloads ===

create table if not exists public.settlement_payloads (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id) on delete cascade,
  claim_id uuid not null references public.claims (id) on delete cascade,
  calculation_id uuid not null,
  settlement_ref text not null,
  -- The whole generated document: components, legs, EIP-712, pacs.008.
  payload jsonb not null,
  -- SHA-256 over the canonical payload. NOT the EIP-712 signing hash.
  digest text not null,
  ready boolean not null default false,
  blockers jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

-- One payload per (claim, agreed calculation). Regenerating for the same
-- calculation is the same document; a recompute is a different one and gets
-- its own row rather than overwriting the record of what was agreed before.
create unique index if not exists uniq_settlement_payloads_calculation
  on public.settlement_payloads (claim_id, calculation_id);

alter table public.settlement_payloads enable row level security;

drop policy if exists "Company members read their own settlement payloads" on public.settlement_payloads;
create policy "Company members read their own settlement payloads"
  on public.settlement_payloads
  for select
  using (public.is_company_member(company_id));

-- No write policy: payloads are generated by the settlement consumer running as
-- service_role. A user-editable settlement instruction is a fraud vector.

-- === 3. Emit claim.settlement_ready on agreement ===
--
-- Extends emit_domain_event() with an 'agreed_claim' branch. The function is
-- replaced wholesale (Postgres has no "add a branch"), so the existing three
-- aggregates are reproduced verbatim below — do not drop them.

create or replace function public.emit_domain_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_aggregate    text := TG_ARGV[0];
  v_event_type   text := TG_ARGV[1];
  v_company_mode text := TG_ARGV[2];
  v_id_column    text := TG_ARGV[3];
  v_company_id   uuid;
  v_aggregate_id uuid;
  v_payload      jsonb;
  v_digest       text;
  v_row          jsonb := to_jsonb(NEW);
begin
  v_aggregate_id := (v_row ->> v_id_column)::uuid;
  if v_aggregate_id is null then
    return NEW;
  end if;

  if v_company_mode = 'self' then
    v_company_id := (v_row ->> 'company_id')::uuid;
  else
    select c.company_id into v_company_id
      from public.claims c
     where c.id = (v_row ->> 'claim_id')::uuid;
  end if;

  if v_company_id is null then
    return NEW;
  end if;

  if v_aggregate = 'claim' then
    v_payload := jsonb_build_object(
      'claim_id', v_aggregate_id,
      'demurrage_amount', NEW.demurrage_amount,
      'despatch_amount', NEW.despatch_amount,
      'currency', NEW.currency,
      'used_hours', NEW.used_hours,
      'allowed_hours', NEW.allowed_hours
    );
  elsif v_aggregate = 'pre_arrival_risk' then
    v_payload := jsonb_build_object(
      'risk_id', v_aggregate_id,
      'claim_id', NEW.claim_id,
      'decision_grade', NEW.decision_grade,
      'demurrage_probability', NEW.demurrage_probability,
      'expected_exposure', NEW.expected_exposure,
      'currency', NEW.currency,
      'inputs_digest', NEW.inputs_digest
    );
  elsif v_aggregate = 'settlement' then
    v_payload := jsonb_build_object(
      'settlement_id', NEW.id,
      'claim_id', NEW.claim_id,
      'status', NEW.status,
      'amount', NEW.amount,
      'currency', NEW.currency
    );
    v_aggregate_id := NEW.claim_id;
  elsif v_aggregate = 'agreed_claim' then
    -- A pointer plus the agreed snapshot, per the outbox's payload rule. The
    -- consumer reads the claim and calculation for everything else.
    v_payload := jsonb_build_object(
      'claim_id', v_aggregate_id,
      'agreed_at', NEW.agreed_at,
      'agreed_calculation_id', NEW.agreed_calculation_id
    );
  else
    v_payload := jsonb_build_object('id', v_aggregate_id);
  end if;

  v_digest := md5(v_payload::text);

  insert into public.domain_events
    (company_id, aggregate, aggregate_id, event_type, payload, idempotency_key)
  values
    (v_company_id, v_aggregate, v_aggregate_id, v_event_type, v_payload,
     v_event_type || ':' || v_aggregate_id::text || ':' || v_digest)
  on conflict (idempotency_key) do nothing;

  return NEW;
end;
$$;

revoke execute on function public.emit_domain_event() from public;
revoke execute on function public.emit_domain_event() from anon;
revoke execute on function public.emit_domain_event() from authenticated;

-- Fires only on the NULL -> NOT NULL transition. Without the WHEN clause every
-- later edit to an agreed claim would re-emit a settlement event, and a
-- downstream processor would see repeated instructions to move money.
drop trigger if exists trg_domain_event_claim_agreed on public.claims;
create trigger trg_domain_event_claim_agreed
  after update of agreed_at on public.claims
  for each row
  when (OLD.agreed_at is null and NEW.agreed_at is not null)
  execute function public.emit_domain_event(
    'agreed_claim', 'claim.settlement_ready', 'self', 'id'
  );

comment on column public.claims.agreed_at is
  'When both sides agreed the calculation. NULL -> NOT NULL emits claim.settlement_ready. Never backfilled.';
comment on table public.settlement_payloads is
  'Generated settlement instructions (EIP-712 + ISO 20022 pacs.008 draft). Written only by the settlement consumer (service_role); never user-editable.';
